version: '3.1'
services:
  db:
    image: postgres:lattest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9hGDhhRm5IsE1aqxfyK44
      - POSTGRES_DB=dibscheduler
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
